import type { Language } from "@/components/lang-context";

export const TERMINAL_ABOUT: Record<Language, string> = {
  en: "Alexis Reyna is a full-stack developer from Nuevo León, Mexico, with two years building and running financial systems and payment flows in production: Stripe and STP/SPEI integrations, back-end development and infrastructure.\n\nHe works across the whole cycle (API, database, infrastructure and deployment) in C#/.NET, Go, Ruby on Rails and TypeScript, and has also built crypto payment systems. Software Engineering at UANL (FIME) · AWS Certified AI Practitioner.",
  es: "Alexis Reyna es un desarrollador full-stack de Nuevo León, México, con dos años construyendo y operando sistemas financieros y flujos de pago en producción: integraciones con Stripe y STP/SPEI, desarrollo de backend y administración de infraestructura.\n\nTrabaja el ciclo completo (API, base de datos, infraestructura y despliegue) en C#/.NET, Go, Ruby on Rails y TypeScript, y también ha desarrollado sistemas de pagos con criptomonedas. Ingeniería de Software en la UANL (FIME) · AWS Certified AI Practitioner.",
};

export const TERMINAL_COPY = {
  en: {
    compactWelcome: "Full-stack developer",
    compactPlaceholder: "Command or question…", compactAiPlaceholder: "Ask about Alexis…",
    touchHint: "Tap ↑ to send", touchBusyHint: "Tap ■ to stop",
    backToMenu: "← Back to menu",
    title: "Alexis Reyna · Projects portfolio", welcome: "Full-stack developer. Welcome to my corner of the internet.",
    intro: "Choose a destination, type a command, or ask me a question.", aboutPhoto: "Portrait of Alexis Reyna",
    projects: "Projects", about: "About me", contact: "Contact", ai: "Talk to Alexis AI version",
    projectHint: "Explore selected work", aboutHint: "Background & skills", contactHint: "Send Alexis a message", aiHint: "Start a conversation",
    menuHint: "↑ ↓ navigate · enter select", placeholder: "Type a command or a question…", aiPlaceholder: "Ask about Alexis, his work, or an idea…",
    assistantIntro: "You're chatting with Alexis's AI assistant. Ask about his experience, his projects, or hiring him.",
    examples: ["Walk me through your payments experience", "What did you own at Inverater?", "Are you open to new roles?"],
    // Conversation openers, index-aligned across languages: one per page load, the next one on every reload.
    openers: [
      "What did a normal day at Inverater actually look like?", "Sell me on the Beatles. You get one song.", "React or Vue? Yes, I'm starting an argument.",
      "Who are you when LinkedIn isn't watching?", "Does payment code make you triple-check every zero?", "Be honest: is the coffee a hobby or a dependency?",
      "You, Cursor, ChatGPT… who's doing the group project?", "Free plane ticket. Where are you going?", "Ever moved a button one pixel and called it a day?",
      "Got a dev joke? My standards are worrying.", "Startup or big tech? You can't say 'it depends.'", "I've got an idea. Famous last words, right?",
      "What's a 'quick fix' that ate your whole afternoon?", "Explain your favorite project like we're waiting for tacos.",
      "What's your most harmless unpopular opinion?", "How many browser tabs before it counts as a cry for help?",
      "A whole day without screens. What's the plan?", "What song gets played until everyone asks you to stop?",
      "Which side project got wildly out of hand?", "What's something you're bad at but enjoy anyway?",
    ],
    projectsIntro: "Selected projects — choose one to open it in Finder.", contactIntro: "Leave a message. Alexis will reply to your email.",
    help: "Available commands", helpHint: "Tab completes commands. ↑ ↓ recall input. Shift+Enter adds a line. Esc stops a reply.",
    menu: "Show the main menu", clear: "Clear this conversation", exit: "Return to the portfolio shell",
    shell: "Portfolio shell", assistant: "AI assistant", ready: "ready", thinking: "Thinking", writing: "Writing", done: "Completed", stopped: "Interrupted", stop: "Stop reply", send: "Send", retry: "Retry", latest: "↓ Latest output",
    inputHint: "enter send · shift+enter newline", shortHint: "enter send", busyHint: "esc stop · draft your next message", commandHint: "/help for commands",
    error: "The reply could not be completed. Try again or explore the portfolio.", rateLimit: "Chat limit reached. Try again later; projects and contact are still available.", timeout: "The reply took too long. You can try again.", details: "Error details",
    unknown: "Command not found. Use /help to see available commands.", opened: "Opened project", returned: "Back in the portfolio shell. Type /menu for destinations or /ai to chat.",
    close: "Close terminal", minimize: "Minimize terminal", maximize: "Maximize terminal", restore: "Restore terminal", transcript: "Terminal output", draft: "Terminal input",
  },
  es: {
    compactWelcome: "Desarrollador full-stack",
    compactPlaceholder: "Comando o pregunta…", compactAiPlaceholder: "Pregunta por Alexis…",
    touchHint: "Toca ↑ para enviar", touchBusyHint: "Toca ■ para detener",
    backToMenu: "← Volver al menú",
    title: "Alexis Reyna · portfolio de proyectos", welcome: "Desarrollador full-stack. Bienvenido a mi rincón de internet.",
    intro: "Elige un destino, escribe un comando o hazme una pregunta.", aboutPhoto: "Retrato de Alexis Reyna",
    projects: "Proyectos", about: "Sobre mí", contact: "Contacto", ai: "Habla con la versión IA de Alexis",
    projectHint: "Explora mi trabajo", aboutHint: "Experiencia y habilidades", contactHint: "Envíale un mensaje a Alexis", aiHint: "Inicia una conversación",
    menuHint: "↑ ↓ navegar · enter seleccionar", placeholder: "Escribe un comando o una pregunta…", aiPlaceholder: "Pregunta sobre Alexis, su trabajo o una idea…",
    assistantIntro: "Estás hablando con el asistente IA de Alexis. Pregunta por su experiencia, sus proyectos o cómo contratarlo.",
    examples: ["Cuéntame tu experiencia en pagos", "¿De qué eras responsable en Inverater?", "¿Estás abierto a nuevas oportunidades?"],
    openers: [
      "A ver, ¿cómo era un día normal en Inverater?", "Convénceme de escuchar a los Beatles. Una canción.", "¿React o Vue? Sí, vengo a armar pleito.",
      "¿Quién eres cuando LinkedIn no te está viendo?", "¿Programando pagos revisas cada cero tres veces?", "La neta: ¿lo del café es gusto o dependencia?",
      "Tú, Cursor y ChatGPT… ¿quién hace la tarea?", "Te regalo un vuelo. ¿A dónde te vas?", "¿Has movido un botón un píxel y dicho 'ya quedó'?",
      "Échate un chiste de devs. Me río con poco.", "¿Startup o big tech? No se vale decir 'depende'.", "Tengo una idea. Así empiezan los problemas, ¿no?",
      "¿Qué 'arreglito rápido' te robó toda la tarde?", "Cuéntame tu proyecto favorito como si esperáramos tacos.",
      "¿Qué opinión tuya arma debate hasta en la sobremesa?", "¿Cuántas pestañas abiertas ya cuentan como pedir auxilio?",
      "Un día entero sin pantallas. ¿Qué se arma?", "¿Qué canción repites hasta que te esconden la bocina?",
      "¿Qué proyectito se te salió de las manos?", "¿Qué haces por gusto aunque te salga medio chueco?",
    ],
    projectsIntro: "Proyectos seleccionados — elige uno para abrirlo en Finder.", contactIntro: "Deja un mensaje. Alexis responderá a tu correo.",
    help: "Comandos disponibles", helpHint: "Tab completa comandos. ↑ ↓ recuperan entradas. Shift+Enter agrega una línea. Esc detiene la respuesta.",
    menu: "Mostrar el menú principal", clear: "Borrar esta conversación", exit: "Volver a la terminal del portfolio",
    shell: "Terminal del portfolio", assistant: "Asistente IA", ready: "listo", thinking: "Pensando", writing: "Escribiendo", done: "Completado", stopped: "Interrumpido", stop: "Detener respuesta", send: "Enviar", retry: "Reintentar", latest: "↓ Última salida",
    inputHint: "enter enviar · shift+enter nueva línea", shortHint: "enter enviar", busyHint: "esc detener · prepara tu mensaje", commandHint: "/help para ver comandos",
    error: "No se pudo completar la respuesta. Intenta de nuevo o explora el portfolio.", rateLimit: "Límite del chat alcanzado. Intenta más tarde; proyectos y contacto siguen disponibles.", timeout: "La respuesta tardó demasiado. Puedes intentarlo de nuevo.", details: "Detalles del error",
    unknown: "Comando no encontrado. Usa /help para ver los comandos disponibles.", opened: "Proyecto abierto", returned: "De vuelta en la terminal. Escribe /menu para explorar o /ai para conversar.",
    close: "Cerrar terminal", minimize: "Minimizar terminal", maximize: "Maximizar terminal", restore: "Restaurar terminal", transcript: "Salida de la terminal", draft: "Entrada de la terminal",
  },
} satisfies Record<Language, object>;
