import type { Language } from "@/components/lang-context";

export const TERMINAL_ABOUT: Record<Language, string> = {
  en: "Alexis Reyna is a full-stack developer from Nuevo León, Mexico, with two years building and running financial systems and payment flows in production: Stripe and STP/SPEI integrations, back-end development and infrastructure.\n\nHe works across the whole cycle (API, database, infrastructure and deployment) in C#/.NET, Go, Ruby on Rails and TypeScript, and has also built crypto payment systems. Software Engineering at UANL (FIME) · AWS Certified AI Practitioner.",
  es: "Alexis Reyna es un desarrollador full-stack de Nuevo León, México, con dos años construyendo y operando sistemas financieros y flujos de pago en producción: integraciones con Stripe y STP/SPEI, desarrollo de backend y administración de infraestructura.\n\nTrabaja el ciclo completo (API, base de datos, infraestructura y despliegue) en C#/.NET, Go, Ruby on Rails y TypeScript, y también ha desarrollado sistemas de pagos con criptomonedas. Ingeniería de Software en la UANL (FIME) · AWS Certified AI Practitioner.",
  zh: "Alexis Reyna 是来自墨西哥新莱昂州的全栈开发者，拥有两年在生产环境中构建和运维金融系统与支付流程的经验：Stripe 与 STP/SPEI 集成、后端开发和基础设施管理。\n\n他负责完整的开发周期（API、数据库、基础设施与部署），使用 C#/.NET、Go、Ruby on Rails 和 TypeScript，也开发过加密货币支付系统。UANL（FIME）软件工程专业 · AWS Certified AI Practitioner。",
};

export const TERMINAL_COPY = {
  en: {
    compactWelcome: "Full-stack developer",
    compactPlaceholder: "Command or question…", compactAiPlaceholder: "Ask about Alexis…",
    touchHint: "Tap ↑ to send", touchBusyHint: "Tap ■ to stop",
    backToMenu: "← Back to menu",
    title: "Alexis Reyna · Projects portfolio", welcome: "Full-stack developer. Welcome to my corner of the internet.",
    intro: "Choose a destination, type a command, or ask me a question.", aboutPhoto: "Portrait of Alexis Reyna",
    projects: "Projects", about: "About me", contact: "Contact", ai: "Talk to Alexis AI version",
    projectHint: "Explore selected work", aboutHint: "Background & skills", contactHint: "Send Alexis a message", aiHint: "Start a conversation",
    menuHint: "↑ ↓ navigate · enter select", placeholder: "Type a command or a question…", aiPlaceholder: "Ask about Alexis, his work, or an idea…",
    assistantIntro: "You're chatting with Alexis's AI assistant. Ask about his projects, skills, or working together.",
    examples: ["What have you built?", "What are your technical skills?", "How can we work together?"],
    // Conversation openers, index-aligned across languages: one per page load, the next one on every reload.
    openers: [
      "What are you building at Inverater?", "Which Beatles album should I start with?", "React or Vue? Pick a side.",
      "Tell me about you, minus the résumé.", "What makes banking code so tricky?", "Convince me coffee beats sleep.",
      "Cursor or ChatGPT: who's your copilot?", "What's first on your travel bucket list?", "How do you know a UI feels right?",
      "Tell me a joke only devs would get.", "Startup life or big tech: what's next?", "Could we build something together?",
    ],
    projectsIntro: "Selected projects — choose one to open it in Finder.", contactIntro: "Leave a message. Alexis will reply to your email.",
    help: "Available commands", helpHint: "Tab completes commands. ↑ ↓ recall input. Shift+Enter adds a line. Esc stops a reply.",
    menu: "Show the main menu", clear: "Clear this conversation", exit: "Return to the portfolio shell",
    shell: "Portfolio shell", assistant: "AI assistant", ready: "ready", thinking: "Thinking", writing: "Writing", done: "Completed", stopped: "Interrupted", stop: "Stop reply", send: "Send", retry: "Retry", latest: "↓ Latest output",
    inputHint: "enter send · shift+enter newline", shortHint: "enter send", busyHint: "esc stop · draft your next message", commandHint: "/help for commands",
    error: "The reply could not be completed. Try again or explore the portfolio.", rateLimit: "Chat limit reached. Try again later; projects and contact are still available.", timeout: "The reply took too long. You can try again.", details: "Error details",
    unknown: "Command not found. Use /help to see available commands.", opened: "Opened project", returned: "Back in the portfolio shell. Type /menu for destinations or /ai to chat.",
    close: "Close terminal", minimize: "Minimize terminal", maximize: "Maximize terminal", restore: "Restore terminal", transcript: "Terminal output", draft: "Terminal input",
  },
  es: {
    compactWelcome: "Desarrollador full-stack",
    compactPlaceholder: "Comando o pregunta…", compactAiPlaceholder: "Pregunta por Alexis…",
    touchHint: "Toca ↑ para enviar", touchBusyHint: "Toca ■ para detener",
    backToMenu: "← Volver al menú",
    title: "Alexis Reyna · portfolio de proyectos", welcome: "Desarrollador full-stack. Bienvenido a mi rincón de internet.",
    intro: "Elige un destino, escribe un comando o hazme una pregunta.", aboutPhoto: "Retrato de Alexis Reyna",
    projects: "Proyectos", about: "Sobre mí", contact: "Contacto", ai: "Habla con la versión IA de Alexis",
    projectHint: "Explora mi trabajo", aboutHint: "Experiencia y habilidades", contactHint: "Envíale un mensaje a Alexis", aiHint: "Inicia una conversación",
    menuHint: "↑ ↓ navegar · enter seleccionar", placeholder: "Escribe un comando o una pregunta…", aiPlaceholder: "Pregunta sobre Alexis, su trabajo o una idea…",
    assistantIntro: "Estás hablando con el asistente IA de Alexis. Pregunta por sus proyectos, habilidades o cómo trabajar juntos.",
    examples: ["¿Qué proyectos has creado?", "¿Cuáles son tus habilidades técnicas?", "¿Cómo podemos trabajar juntos?"],
    openers: [
      "¿Qué estás construyendo en Inverater?", "¿Con qué disco de los Beatles empiezo?", "¿React o Vue? Elige bando.",
      "Cuéntame sobre ti, sin el currículum.", "¿Qué es lo difícil de programar pagos?", "Convénceme: el café le gana al sueño.",
      "Cursor o ChatGPT: ¿cuál es tu copiloto?", "¿Qué va primero en tu lista de viajes?", "¿Cómo sabes que una UI se siente bien?",
      "Cuéntame un chiste para devs.", "Tu carrera: ¿startup o big tech?", "¿Podemos construir algo juntos?",
    ],
    projectsIntro: "Proyectos seleccionados — elige uno para abrirlo en Finder.", contactIntro: "Deja un mensaje. Alexis responderá a tu correo.",
    help: "Comandos disponibles", helpHint: "Tab completa comandos. ↑ ↓ recuperan entradas. Shift+Enter agrega una línea. Esc detiene la respuesta.",
    menu: "Mostrar el menú principal", clear: "Borrar esta conversación", exit: "Volver a la terminal del portfolio",
    shell: "Terminal del portfolio", assistant: "Asistente IA", ready: "listo", thinking: "Pensando", writing: "Escribiendo", done: "Completado", stopped: "Interrumpido", stop: "Detener respuesta", send: "Enviar", retry: "Reintentar", latest: "↓ Última salida",
    inputHint: "enter enviar · shift+enter nueva línea", shortHint: "enter enviar", busyHint: "esc detener · prepara tu mensaje", commandHint: "/help para ver comandos",
    error: "No se pudo completar la respuesta. Intenta de nuevo o explora el portfolio.", rateLimit: "Límite del chat alcanzado. Intenta más tarde; proyectos y contacto siguen disponibles.", timeout: "La respuesta tardó demasiado. Puedes intentarlo de nuevo.", details: "Detalles del error",
    unknown: "Comando no encontrado. Usa /help para ver los comandos disponibles.", opened: "Proyecto abierto", returned: "De vuelta en la terminal. Escribe /menu para explorar o /ai para conversar.",
    close: "Cerrar terminal", minimize: "Minimizar terminal", maximize: "Maximizar terminal", restore: "Restaurar terminal", transcript: "Salida de la terminal", draft: "Entrada de la terminal",
  },
  zh: {
    compactWelcome: "全栈开发者",
    compactPlaceholder: "输入命令或问题…", compactAiPlaceholder: "询问 Alexis…",
    touchHint: "点按 ↑ 发送", touchBusyHint: "点按 ■ 停止",
    backToMenu: "← 返回菜单",
    title: "Alexis Reyna · 项目作品集", welcome: "全栈开发者。欢迎来到我的互联网小天地。",
    intro: "选择一个目的地，输入命令，或直接提问。", aboutPhoto: "Alexis Reyna 的照片",
    projects: "项目", about: "关于我", contact: "联系", ai: "和 AI 版 Alexis 聊聊",
    projectHint: "探索精选作品", aboutHint: "经历与技能", contactHint: "给 Alexis 留言", aiHint: "开始对话",
    menuHint: "↑ ↓ 导航 · enter 选择", placeholder: "输入命令或问题…", aiPlaceholder: "询问 Alexis、他的工作或一个想法…",
    assistantIntro: "你正在与 Alexis 的 AI 助手聊天。可以询问他的项目、技能或合作方式。",
    examples: ["你做过哪些项目？", "你有哪些技术技能？", "我们如何合作？"],
    openers: [
      "你在 Inverater 开发什么？", "Beatles 的专辑该从哪张听起？", "React 还是 Vue？选一边。",
      "撇开履历，讲讲你的故事。", "写支付代码难在哪里？", "说服我：咖啡比睡觉更重要。",
      "Cursor 还是 ChatGPT：谁是你的副驾驶？", "你的旅行愿望清单上第一个是哪里？", "怎样的 UI 才让你觉得对？",
      "讲个只有码农才懂的笑话。", "创业公司还是大厂：你的职业下一步？", "想和你合作，该怎么联系？",
    ],
    projectsIntro: "精选项目 — 选择一个在 Finder 中打开。", contactIntro: "请留言。Alexis 将通过电子邮件回复。",
    help: "可用命令", helpHint: "Tab 补全命令。↑ ↓ 浏览输入历史。Shift+Enter 换行。Esc 停止回复。",
    menu: "显示主菜单", clear: "清除此对话", exit: "返回作品集终端",
    shell: "作品集终端", assistant: "AI 助手", ready: "就绪", thinking: "思考中", writing: "正在输入", done: "已完成", stopped: "已中断", stop: "停止回复", send: "发送", retry: "重试", latest: "↓ 最新输出",
    inputHint: "enter 发送 · shift+enter 换行", shortHint: "enter 发送", busyHint: "esc 停止 · 起草下一条消息", commandHint: "/help 查看命令",
    error: "无法完成回复。请重试或浏览作品集。", rateLimit: "已达到聊天限制。请稍后重试；仍可查看项目和联系方式。", timeout: "回复超时。你可以重试。", details: "错误详情",
    unknown: "未找到命令。输入 /help 查看可用命令。", opened: "已打开项目", returned: "已返回作品集终端。输入 /menu 浏览或 /ai 聊天。",
    close: "关闭终端", minimize: "最小化终端", maximize: "最大化终端", restore: "恢复终端", transcript: "终端输出", draft: "终端输入",
  },
} satisfies Record<Language, object>;
